[tool.poetry]
name = "webex-assistant-sdk"
version = "0.2.0"
description = "An SDK for developing applications for Webex Assistant."
readme = "README.md"
authors = ["Minh Vo Thanh <minhtue@cisco.com>", "J.J. Jackson <jdot@cisco.com>"]
license = "MIT"
keywords = ['webex', 'webex-assistant', 'webex-teams']
classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
]


[tool.poetry.dependencies]
python = "^3.6"
# cryptography maintains backward compatibility for 3 minor versions
# and each 10th minor release is major (2.8 -> 2.9 -> 3.0 ...)
cryptography = ">=2.8,<3.4"
mindmeld = "^4.3.1"
requests = "^2.22.0"
spacy = "^2.3.0"

[tool.poetry.dev-dependencies]
black = '^20.8b0'
flake8 = '^3.7.8'
isort = {version = '^4.3', extras = ['toml']}
pre-commit = '^1.18'
pylint = '^2.3.1'
pytest = '^5.1'
pytest-cov = "^2.8.1"
tox = "^3.14.0"

[tool.poetry.scripts]
wxa_sdk = 'webex_assistant_sdk.__main__:main'

[tool.isort]
force_sort_within_sections = true
include_trailing_comma = true
line_length = 100
multi_line_output = 3
sections = ['FUTURE', 'STDLIB', 'TRANSITIONAL', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
default_section = 'THIRDPARTY'
known_first_party = ['webex_assistant_sdk']
skip_glob = ['scripts', 'venv*']


[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py36']

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
